name: module_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  appwrite: ^11.0.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.7.3
  firebase_core: ^2.22.0
  firebase_messaging: ^14.6.6
  flutter:
    sdk: flutter

  flutter_local_notifications: ^15.1.0+1
  get: 4.6.5
  google_fonts: ^6.1.0
  http: ^1.0.0
  image_picker: ^1.0.4
  webview_flutter: ^4.4.1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  get_test: ^4.0.1
  mockito: ^5.4.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logoo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: ebGaramond
      fonts:
        - asset: assets/fonts/eb_garamond.ttf
  uses-material-design: true
